from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass
import shutil
import subprocess
import tempfile
import re
import pandas as pd


@dataclass
class PocketRunResult:
    tool: str
    available: bool
    output_dir: str | None
    table: pd.DataFrame
    message: str


def tool_available(name: str) -> bool:
    return shutil.which(name) is not None


def run_fpocket_on_pdb(pdb_path: str | Path, output_dir: str | Path | None = None) -> PocketRunResult:
    """Run fpocket on a single PDB frame and parse a coarse pocket table.

    Requires an external fpocket installation on PATH. The adapter is intentionally
    non-fatal: if fpocket is unavailable or parsing fails, the UI shows a clear
    diagnostic rather than crashing.
    """
    pdb_path = Path(pdb_path)
    if not tool_available("fpocket"):
        return PocketRunResult("fpocket", False, None, pd.DataFrame(), "fpocket was not found on PATH.")
    out_parent = Path(output_dir) if output_dir else pdb_path.parent
    cmd = ["fpocket", "-f", str(pdb_path)]
    try:
        subprocess.run(cmd, cwd=str(out_parent), check=True, capture_output=True, text=True, timeout=300)
    except Exception as exc:
        return PocketRunResult("fpocket", True, None, pd.DataFrame(), f"fpocket execution failed: {exc}")
    out_dir = out_parent / f"{pdb_path.stem}_out"
    info_files = list(out_dir.glob("*_info.txt")) if out_dir.exists() else []
    rows = []
    for info in info_files:
        txt = info.read_text(errors="ignore")
        for block in re.split(r"Pocket\s+\d+\s*:", txt)[1:]:
            nums = {}
            for line in block.splitlines():
                m = re.match(r"\s*([A-Za-z0-9_ .-]+)\s*:\s*([-+]?\d*\.?\d+)", line)
                if m:
                    key = m.group(1).strip().lower().replace(" ", "_")
                    nums[key] = float(m.group(2))
            if nums:
                rows.append(nums)
    return PocketRunResult("fpocket", True, str(out_dir), pd.DataFrame(rows), "fpocket completed.")


def make_povme_template(output_path: str | Path, inclusion_sphere_center=(0.0, 0.0, 0.0), radius_A: float = 12.0) -> str:
    """Write a POVME-style configuration template for users to adapt.

    Full POVME execution is environment-specific, so TrajSem provides a reproducible
    template and accepts POVME CSV output in the app.
    """
    text = f"""# POVME configuration template generated by TrajSem
# Replace trajectory/path fields with your local files and adjust the inclusion sphere.
GridSpacing            1.0
DistanceCutoff         1.09
ConvexHullExclusion    true
SavePocketVolumes      true
OutputFilenamePrefix   trajsem_povme

# Inclusion sphere: center_x center_y center_z radius
PointsInclusionSphere  {inclusion_sphere_center[0]:.3f} {inclusion_sphere_center[1]:.3f} {inclusion_sphere_center[2]:.3f} {radius_A:.3f}
"""
    output_path = Path(output_path)
    output_path.write_text(text)
    return str(output_path)


def normalize_pocket_volume_table(file) -> pd.DataFrame:
    """Accept common fpocket/POVME/MDpocket CSV-like outputs and return time/pocket volume columns."""
    df = pd.read_csv(file)
    cols = {c.lower().strip(): c for c in df.columns}
    out = pd.DataFrame()
    for candidate in ["time_ns", "time", "t"]:
        if candidate in cols:
            out["time_ns"] = pd.to_numeric(df[cols[candidate]], errors="coerce")
            break
    if "time_ns" not in out:
        out["time_ns"] = range(len(df))
    for candidate in ["pocket_volume_a3", "volume", "volume_a3", "pocket_volume", "pocket_volume_angstrom3"]:
        if candidate in cols:
            out["pocket_volume_A3"] = pd.to_numeric(df[cols[candidate]], errors="coerce")
            break
    if "pocket_volume_A3" not in out:
        # Substring fallback: look for any column containing "vol" (case-insensitive).
        for orig_col in df.columns:
            if "vol" in orig_col.lower() and orig_col.lower().strip() not in {"time_ns", "time", "t"}:
                out["pocket_volume_A3"] = pd.to_numeric(df[orig_col], errors="coerce")
                break
    if "pocket_volume_A3" not in out:
        numeric = df.select_dtypes(include="number")
        if len(numeric.columns):
            out["pocket_volume_A3"] = numeric.iloc[:, -1]
    return out
