from __future__ import annotations

from datetime import datetime
import pandas as pd
from .events import Event


def summarize_metrics(df: pd.DataFrame) -> dict:
    out = {"frames": int(len(df))}
    if "time_ns" in df.columns and len(df):
        out["duration_ns"] = round(float(df["time_ns"].max() - df["time_ns"].min()), 3)
    for col in df.select_dtypes(include="number").columns:
        if col == "time_ns":
            continue
        s = df[col].dropna()
        if len(s):
            out[col] = {
                "mean": round(float(s.mean()), 4),
                "median": round(float(s.median()), 4),
                "min": round(float(s.min()), 4),
                "max": round(float(s.max()), 4),
            }
    return out


def stability_label(df: pd.DataFrame, events: list[Event]) -> tuple[str, str]:
    high = [e for e in events if e.severity == "high"]
    drift = any(e.event_type == "ligand_pose_drift" for e in events)
    hbonds = [e for e in events if e.event_type == "persistent_hydrogen_bond"]
    if drift and hbonds:
        return (
            "Rearranged but partially restabilized",
            "The ligand shows substantial movement but later forms persistent stabilizing interactions.",
        )
    if drift:
        return (
            "Potentially unstable",
            "A sustained ligand RMSD increase suggests pose instability or transition to another binding mode.",
        )
    if hbonds and not high:
        return (
            "Stable",
            "Persistent interactions and absence of major drift support a stable binding pose.",
        )
    return (
        "Indeterminate",
        "The available descriptors are insufficient for a strong stability claim.",
    )


# ---------------------------------------------------------------------------
# Human-readable labels for well-known descriptor columns
# ---------------------------------------------------------------------------
_DESCRIPTOR_LABELS: dict[str, str] = {
    "protein_rmsd_A": "Protein RMSD (Å)",
    "ligand_rmsd_A": "Ligand RMSD (Å)",
    "radius_of_gyration_A": "Radius of Gyration (Å)",
    "pocket_volume_A3": "Pocket Volume (ų)",
    "hbond_approx_count": "H-bond Approx. Count",
    "salt_bridge_count": "Salt Bridge Count",
    "water_bridge_count": "Water Bridge Count",
    "pi_interaction_count": "π-Interaction Count",
    "binding_site_sasa_A2": "Binding-Site SASA (Ų)",
    "loop_185_193_displacement_A": "Loop 185–193 Displacement (Å)",
    "hbond_asp147_occupancy": "H-bond ASP147 Occupancy",
    "hbond_lys203_occupancy": "H-bond LYS203 Occupancy",
    "contact_phe91_occupancy": "Contact PHE91 Occupancy",
    "pi_min_centroid_distance_A": "π Centroid Distance (Å)",
    "pi_min_plane_angle_deg": "π Plane Angle (°)",
}


def _label(col: str) -> str:
    return _DESCRIPTOR_LABELS.get(col, col.replace("_", " ").title())


def _severity_icon(severity: str) -> str:
    return {"high": "🔴", "moderate": "🟡", "low": "🟢"}.get(severity.lower(), "⚪")


def make_markdown_report(
    df: pd.DataFrame,
    events: list[Event],
    project_name: str = "TrajSem analysis",
) -> str:
    """
    Generate a fully data-driven Markdown report that mirrors the three main
    TrajSem UI tabs:

      1. Overview  — trajectory-level stats and stability assessment
      2. Features  — per-descriptor statistics table (all numeric columns)
      3. Semantic Events — every detected event with time window, confidence,
                           severity, evidence key-values, and interpretation

    No placeholder or template text is included; every claim is derived from
    the supplied ``df`` and ``events``.
    """
    metrics = summarize_metrics(df)
    label, rationale = stability_label(df, events)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    n_frames = metrics.get("frames", len(df))
    duration = metrics.get("duration_ns", None)
    duration_str = f"**{duration} ns**" if duration is not None else "unknown duration"

    lines: list[str] = [
        f"# {project_name}",
        "",
        f"*Generated by TrajSem · {now}*",
        "",
        "---",
        "",
        "## 1. Overview",
        "",
        "### Trajectory summary",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| Frames analysed | {n_frames:,} |",
        f"| Simulation duration | {duration_str} |",
        f"| Semantic events detected | {len(events)} |",
        f"| Stability assessment | **{label}** |",
        "",
        f"> {rationale}",
        "",
    ]

    # Core descriptors shown on the Overview tab
    overview_cols = [
        "protein_rmsd_A",
        "ligand_rmsd_A",
        "radius_of_gyration_A",
        "pocket_volume_A3",
        "hbond_approx_count",
        "salt_bridge_count",
        "water_bridge_count",
        "pi_interaction_count",
    ]
    overview_rows = [(col, metrics[col]) for col in overview_cols if col in metrics]
    if overview_rows:
        lines += [
            "### Key descriptor ranges",
            "",
            "| Descriptor | Mean | Median | Min | Max |",
            "|---|---|---|---|---|",
        ]
        for col, s in overview_rows:
            lines.append(
                f"| {_label(col)} | {s['mean']} | {s['median']} | {s['min']} | {s['max']} |"
            )
        lines.append("")

    # -------------------------------------------------------------------------
    # Section 2 — Features: full descriptor stats (mirrors the Features tab table)
    # -------------------------------------------------------------------------
    lines += [
        "---",
        "",
        "## 2. Features",
        "",
        "Full per-descriptor statistics extracted from the trajectory.",
        "",
        "| Descriptor | Mean | Median | Min | Max |",
        "|---|---|---|---|---|",
    ]
    for col, v in metrics.items():
        if isinstance(v, dict) and {"mean", "median", "min", "max"} <= v.keys():
            lines.append(
                f"| {_label(col)} | {v['mean']} | {v['median']} | {v['min']} | {v['max']} |"
            )
    lines.append("")

    # -------------------------------------------------------------------------
    # Section 3 — Semantic Events (mirrors the Semantic Events tab)
    # -------------------------------------------------------------------------
    lines += [
        "---",
        "",
        "## 3. Semantic Events",
        "",
    ]

    if not events:
        lines += [
            "No semantic events passed the current detection thresholds.",
            "",
            "> This does not mean the trajectory is uneventful — it means the present "
            "descriptor set did not support a confident event call with the current parameters.",
            "",
        ]
    else:
        for i, ev in enumerate(events, 1):
            icon = _severity_icon(ev.severity)
            t0, t1 = ev.time_window_ns
            lines += [
                f"### E{i}. {ev.title}",
                "",
                "| Property | Value |",
                "|---|---|",
                f"| Event type | `{ev.event_type}` |",
                f"| Time window | {t0:.3f} – {t1:.3f} ns |",
                f"| Confidence | {ev.confidence:.2f} |",
                f"| Severity | {icon} {ev.severity.capitalize()} |",
                f"| Verification | `{ev.verification_status}` |",
            ]
            if ev.frame_window:
                lines.append(f"| Frame window | {ev.frame_window[0]} – {ev.frame_window[1]} |")
            if ev.entities:
                for k, v in ev.entities.items():
                    lines.append(f"| Entity · {k} | {v} |")
            lines.append("")

            if ev.evidence:
                lines += [
                    "**Evidence:**",
                    "",
                    "| Key | Value |",
                    "|---|---|",
                ]
                for k, v in ev.evidence.items():
                    val_str = (
                        ", ".join(str(x) for x in v) if isinstance(v, list) else str(v)
                    )
                    lines.append(f"| `{k}` | {val_str} |")
                lines.append("")

            lines += [
                f"**Interpretation:** {ev.interpretation}",
                "",
            ]

    # -------------------------------------------------------------------------
    lines += [
        "---",
        "",
        "## Limitations",
        "",
        "- This report is an evidence-linked first pass generated entirely from the "
        "extracted descriptor table and detected events.",
        "- All claims are grounded in the supplied data; no thermodynamic, causal, or "
        "affinity inferences are made beyond what the evidence supports.",
        "- Results should not be treated as proof of mechanism without visual frame "
        "inspection, replicate simulations, and, where relevant, longer or enhanced sampling.",
        "",
    ]

    return "\n".join(lines)
